// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kugklbxirypqjzojbjov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z2tsYnhpcnlwcWp6b2piam92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTE3NzgsImV4cCI6MjA2NzIyNzc3OH0.WNrUqEXBAD6zbHUNRfvzOkclnbypWCUJOjHUD4NccRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});